import type {
  Banner,
  CatalogGroup,
  Category,
  Product,
  Store,
  Address,
  Order,
  ShippingOption,
} from "./types";

export const banners: Banner[] = [
  {
    id: "b1",
    title: "Harbolnas 12.12",
    subtitle: "Diskon hingga 90% untuk semua kategori",
    imageUrl: "",
    linkUrl: "/search?promo=harbolnas",
    bgColor: "from-orange-500 to-red-600",
  },
  {
    id: "b2",
    title: "Fashion Week",
    subtitle: "Koleksi terbaru brand lokal pilihan",
    imageUrl: "",
    linkUrl: "/category/fashion",
    bgColor: "from-purple-500 to-pink-600",
  },
  {
    id: "b3",
    title: "Gadget Terbaru",
    subtitle: "Smartphone & aksesoris dengan harga terbaik",
    imageUrl: "",
    linkUrl: "/category/elektronik",
    bgColor: "from-blue-500 to-cyan-600",
  },
];

export const catalogGroups: CatalogGroup[] = [
  { id: "cg1", name: "Belanja", slug: "belanja", icon: "🛍️" },
  { id: "cg2", name: "Kebutuhan Harian", slug: "kebutuhan-harian", icon: "🏪" },
  { id: "cg3", name: "Tagihan", slug: "tagihan", icon: "📄" },
  { id: "cg4", name: "Top-Up", slug: "top-up", icon: "💳" },
  { id: "cg5", name: "Tokopedia Keuangan", slug: "keuangan", icon: "💰" },
  { id: "cg6", name: "Pajak & Pendidikan", slug: "pajak-pendidikan", icon: "🎓" },
  { id: "cg7", name: "Halal Corner", slug: "halal", icon: "🕌" },
  { id: "cg8", name: "Lain - Lain", slug: "lain-lain", icon: "⋯" },
];

export const categories: Category[] = [
  // === Belanja (cg1) L1 ===
  { id: "c1",  name: "Virtual Products",           slug: "virtual-products",    catalogGroupId: "cg1", level: 1 },
  { id: "c2",  name: "Rumah Tangga",               slug: "rumah-tangga",        catalogGroupId: "cg1", level: 1 },
  { id: "c3",  name: "Audio, Kamera & Elektronik Lainnya", slug: "audio-kamera", catalogGroupId: "cg1", level: 1 },
  { id: "c4",  name: "Buku",                       slug: "buku",                catalogGroupId: "cg1", level: 1 },
  { id: "c5",  name: "Dapur",                      slug: "dapur",               catalogGroupId: "cg1", level: 1 },
  { id: "c6",  name: "Elektronik",                 slug: "elektronik",          catalogGroupId: "cg1", level: 1 },
  { id: "c7",  name: "Fashion Anak & Bayi",        slug: "fashion-anak-bayi",   catalogGroupId: "cg1", level: 1 },
  { id: "c8",  name: "Fashion Muslim",             slug: "fashion-muslim",      catalogGroupId: "cg1", level: 1 },
  { id: "c9",  name: "Fashion Pria",               slug: "fashion-pria",        catalogGroupId: "cg1", level: 1 },
  { id: "c10", name: "Fashion Wanita",             slug: "fashion-wanita",      catalogGroupId: "cg1", level: 1 },
  { id: "c11", name: "Film & Musik",               slug: "film-musik",          catalogGroupId: "cg1", level: 1 },
  { id: "c12", name: "Handphone & Tablet",         slug: "handphone-tablet",    catalogGroupId: "cg1", level: 1 },
  { id: "c13", name: "Kecantikan",                 slug: "kecantikan",          catalogGroupId: "cg1", level: 1 },
  { id: "c14", name: "Komputer & Laptop",          slug: "komputer-laptop",     catalogGroupId: "cg1", level: 1 },
  { id: "c15", name: "Olahraga",                   slug: "olahraga",            catalogGroupId: "cg1", level: 1 },
  // L2 under Virtual Products (c1)
  { id: "c1a", name: "Voucher",                    slug: "voucher",             catalogGroupId: "cg1", parentId: "c1", level: 2 },
  // L3 under Voucher (c1a)
  { id: "c1a1", name: "Discount and Shipping Coupon", slug: "discount-coupon", catalogGroupId: "cg1", parentId: "c1a", level: 3 },
  // L2 under Elektronik (c6)
  { id: "c6a", name: "Televisi",                   slug: "televisi",            catalogGroupId: "cg1", parentId: "c6", level: 2 },
  { id: "c6b", name: "AC & Pendingin Udara",       slug: "ac",                  catalogGroupId: "cg1", parentId: "c6", level: 2 },
  { id: "c6c", name: "Mesin Cuci",                 slug: "mesin-cuci",          catalogGroupId: "cg1", parentId: "c6", level: 2 },
  // L3 under Televisi (c6a)
  { id: "c6a1", name: "Smart TV",                  slug: "smart-tv",            catalogGroupId: "cg1", parentId: "c6a", level: 3 },
  { id: "c6a2", name: "LED TV",                    slug: "led-tv",              catalogGroupId: "cg1", parentId: "c6a", level: 3 },
  // L2 under Handphone & Tablet (c12)
  { id: "c12a", name: "Smartphone",                slug: "smartphone",          catalogGroupId: "cg1", parentId: "c12", level: 2 },
  { id: "c12b", name: "Tablet",                    slug: "tablet",              catalogGroupId: "cg1", parentId: "c12", level: 2 },
  { id: "c12c", name: "Aksesoris HP",              slug: "aksesoris-hp",        catalogGroupId: "cg1", parentId: "c12", level: 2 },
  // L3 under Smartphone (c12a)
  { id: "c12a1", name: "Android",                  slug: "android",             catalogGroupId: "cg1", parentId: "c12a", level: 3 },
  { id: "c12a2", name: "iPhone",                   slug: "iphone",              catalogGroupId: "cg1", parentId: "c12a", level: 3 },
  // L2 under Fashion Pria (c9)
  { id: "c9a", name: "Kemeja Pria",                slug: "kemeja-pria",         catalogGroupId: "cg1", parentId: "c9", level: 2 },
  { id: "c9b", name: "Kaos Pria",                  slug: "kaos-pria",           catalogGroupId: "cg1", parentId: "c9", level: 2 },
  { id: "c9c", name: "Celana Pria",                slug: "celana-pria",         catalogGroupId: "cg1", parentId: "c9", level: 2 },
  // L3 under Kemeja Pria
  { id: "c9a1", name: "Kemeja Casual",             slug: "kemeja-casual",       catalogGroupId: "cg1", parentId: "c9a", level: 3 },
  { id: "c9a2", name: "Kemeja Formal",             slug: "kemeja-formal",       catalogGroupId: "cg1", parentId: "c9a", level: 3 },
  // L2 under Komputer & Laptop (c14)
  { id: "c14a", name: "Laptop",                    slug: "laptop",              catalogGroupId: "cg1", parentId: "c14", level: 2 },
  { id: "c14b", name: "PC Desktop",               slug: "pc-desktop",          catalogGroupId: "cg1", parentId: "c14", level: 2 },
  { id: "c14c", name: "Aksesoris Komputer",        slug: "aksesoris-komputer",  catalogGroupId: "cg1", parentId: "c14", level: 2 },
  // L3 under Laptop
  { id: "c14a1", name: "Laptop Gaming",            slug: "laptop-gaming",       catalogGroupId: "cg1", parentId: "c14a", level: 3 },
  { id: "c14a2", name: "Laptop Bisnis",            slug: "laptop-bisnis",       catalogGroupId: "cg1", parentId: "c14a", level: 3 },
  // === Kebutuhan Harian (cg2) ===
  { id: "d1", name: "Makanan & Minuman",           slug: "makanan-minuman",     catalogGroupId: "cg2", level: 1 },
  { id: "d2", name: "Perawatan Pribadi",           slug: "perawatan-pribadi",   catalogGroupId: "cg2", level: 1 },
  { id: "d1a", name: "Snack",                      slug: "snack",               catalogGroupId: "cg2", parentId: "d1", level: 2 },
  { id: "d1b", name: "Minuman Kemasan",            slug: "minuman-kemasan",     catalogGroupId: "cg2", parentId: "d1", level: 2 },
  { id: "d1a1", name: "Keripik",                   slug: "keripik",             catalogGroupId: "cg2", parentId: "d1a", level: 3 },
  { id: "d1a2", name: "Coklat",                    slug: "coklat",              catalogGroupId: "cg2", parentId: "d1a", level: 3 },
];

export const stores: Store[] = [
  { id: "s1", name: "TechStore Official", slug: "techstore", location: "Jakarta", rating: 4.8, totalSold: 12500 },
  { id: "s2", name: "Fashion Hub", slug: "fashion-hub", location: "Bandung", rating: 4.7, totalSold: 8300 },
  { id: "s3", name: "Rumah Indah Shop", slug: "rumah-indah", location: "Surabaya", rating: 4.6, totalSold: 5200 },
];

// Placeholder color swatches
const colors = {
  hitam: "#1a1a1a",
  putih: "#f5f5f5",
  merah: "#ef4444",
  biru: "#3b82f6",
  hijau: "#22c55e",
  abu: "#9ca3af",
};

export const products: Product[] = [
  {
    id: "p1",
    slug: "smartphone-nova-x20",
    name: "Smartphone Nova X20 Pro",
    description: "Smartphone flagship dengan kamera 200MP, prosesor terkencang, dan baterai 5000mAh. Layar AMOLED 6.7 inci 120Hz untuk pengalaman visual terbaik.",
    categoryId: "c4",
    storeId: "s1",
    storeName: "TechStore Official",
    rating: 4.8,
    reviewCount: 2341,
    sold: 15200,
    images: ["", "", ""],
    tags: ["smartphone", "flagship", "kamera"],
    variants: [
      { id: "pv1-1", sku: "NVX20-BLK-128", color: "Hitam", size: "128GB", price: 4999000, stock: 50, images: [""] },
      { id: "pv1-2", sku: "NVX20-BLK-256", color: "Hitam", size: "256GB", price: 5999000, stock: 30, images: [""] },
      { id: "pv1-3", sku: "NVX20-WHT-128", color: "Putih", size: "128GB", price: 4999000, stock: 25, images: [""] },
      { id: "pv1-4", sku: "NVX20-WHT-256", color: "Putih", size: "256GB", price: 5999000, stock: 15, images: [""] },
    ],
  },
  {
    id: "p2",
    slug: "laptop-ultrabook-swift-15",
    name: "Laptop Ultrabook Swift 15",
    description: "Laptop tipis dan ringan dengan prosesor Intel Core i7 generasi terbaru, RAM 16GB, SSD 512GB. Layar IPS 15.6 inci Full HD.",
    categoryId: "c2",
    storeId: "s1",
    storeName: "TechStore Official",
    rating: 4.7,
    reviewCount: 1205,
    sold: 8900,
    images: ["", "", ""],
    tags: ["laptop", "ultrabook", "tipis"],
    variants: [
      { id: "pv2-1", sku: "SWT15-SLV-16-512", color: "Silver", size: "16GB/512GB", price: 12999000, stock: 20, images: [""] },
      { id: "pv2-2", sku: "SWT15-GLD-16-1TB", color: "Gold", size: "16GB/1TB", price: 15999000, stock: 10, images: [""] },
    ],
  },
  {
    id: "p3",
    slug: "kemeja-casual-pria-premium",
    name: "Kemeja Casual Pria Premium",
    description: "Kemeja casual berbahan katun premium 100%, nyaman dipakai seharian. Cocok untuk kerja maupun jalan-jalan.",
    categoryId: "c9",
    storeId: "s2",
    storeName: "Fashion Hub",
    rating: 4.6,
    reviewCount: 892,
    sold: 4500,
    images: ["", "", ""],
    tags: ["kemeja", "pria", "casual"],
    variants: [
      { id: "pv3-1", sku: "KCP-WHT-S", color: "Putih", size: "S", price: 189000, stock: 100, images: [""] },
      { id: "pv3-2", sku: "KCP-WHT-M", color: "Putih", size: "M", price: 189000, stock: 150, images: [""] },
      { id: "pv3-3", sku: "KCP-WHT-L", color: "Putih", size: "L", price: 189000, stock: 120, images: [""] },
      { id: "pv3-4", sku: "KCP-BLU-S", color: "Biru", size: "S", price: 189000, stock: 80, images: [""] },
      { id: "pv3-5", sku: "KCP-BLU-M", color: "Biru", size: "M", price: 189000, stock: 90, images: [""] },
      { id: "pv3-6", sku: "KCP-BLU-L", color: "Biru", size: "L", price: 189000, stock: 70, images: [""] },
    ],
  },
  {
    id: "p4",
    slug: "wireless-earbuds-pro",
    name: "Wireless Earbuds Pro ANC",
    description: "True wireless earbuds dengan Active Noise Cancellation, koneksi Bluetooth 5.3, tahan air IPX5, baterai 30 jam total.",
    categoryId: "c3",
    storeId: "s1",
    storeName: "TechStore Official",
    rating: 4.5,
    reviewCount: 3210,
    sold: 21000,
    images: ["", "", ""],
    tags: ["earbuds", "wireless", "anc"],
    variants: [
      { id: "pv4-1", sku: "WEP-BLK", color: "Hitam", size: undefined, price: 599000, stock: 200, images: [""] },
      { id: "pv4-2", sku: "WEP-WHT", color: "Putih", size: undefined, price: 599000, stock: 180, images: [""] },
    ],
  },
  {
    id: "p5",
    slug: "sepatu-sneakers-urban",
    name: "Sepatu Sneakers Urban Classic",
    description: "Sneakers kasual dengan sol karet anti-licin, bahan canvas premium, cocok untuk gaya sehari-hari.",
    categoryId: "c8",
    storeId: "s2",
    storeName: "Fashion Hub",
    rating: 4.4,
    reviewCount: 654,
    sold: 3200,
    images: ["", "", ""],
    tags: ["sepatu", "sneakers", "casual"],
    variants: [
      { id: "pv5-1", sku: "SSU-BLK-40", color: "Hitam", size: "40", price: 299000, stock: 30, images: [""] },
      { id: "pv5-2", sku: "SSU-BLK-41", color: "Hitam", size: "41", price: 299000, stock: 25, images: [""] },
      { id: "pv5-3", sku: "SSU-BLK-42", color: "Hitam", size: "42", price: 299000, stock: 20, images: [""] },
      { id: "pv5-4", sku: "SSU-WHT-40", color: "Putih", size: "40", price: 299000, stock: 35, images: [""] },
      { id: "pv5-5", sku: "SSU-WHT-41", color: "Putih", size: "41", price: 299000, stock: 30, images: [""] },
    ],
  },
  {
    id: "p6",
    slug: "kursi-ergonomis-kantor",
    name: "Kursi Ergonomis Kantor Pro",
    description: "Kursi kantor ergonomis dengan penyangga lumbar, sandaran kepala adjustable, roda putar 360 derajat.",
    categoryId: "c11",
    storeId: "s3",
    storeName: "Rumah Indah Shop",
    rating: 4.7,
    reviewCount: 445,
    sold: 1800,
    images: ["", "", ""],
    tags: ["kursi", "kantor", "ergonomis"],
    variants: [
      { id: "pv6-1", sku: "KEK-BLK", color: "Hitam", size: undefined, price: 1899000, stock: 15, images: [""] },
      { id: "pv6-2", sku: "KEK-GRY", color: "Abu-abu", size: undefined, price: 1899000, stock: 10, images: [""] },
    ],
  },
  {
    id: "p7",
    slug: "kaos-polos-premium",
    name: "Kaos Polos Premium Cotton",
    description: "Kaos polos berbahan cotton combed 30s, adem, tidak mudah kusut, tersedia banyak warna.",
    categoryId: "c10",
    storeId: "s2",
    storeName: "Fashion Hub",
    rating: 4.5,
    reviewCount: 1567,
    sold: 9800,
    images: ["", "", ""],
    tags: ["kaos", "polos", "cotton"],
    variants: [
      { id: "pv7-1", sku: "KPP-BLK-S", color: "Hitam", size: "S", price: 75000, stock: 200, images: [""] },
      { id: "pv7-2", sku: "KPP-BLK-M", color: "Hitam", size: "M", price: 75000, stock: 250, images: [""] },
      { id: "pv7-3", sku: "KPP-BLK-L", color: "Hitam", size: "L", price: 75000, stock: 200, images: [""] },
      { id: "pv7-4", sku: "KPP-WHT-S", color: "Putih", size: "S", price: 75000, stock: 180, images: [""] },
      { id: "pv7-5", sku: "KPP-WHT-M", color: "Putih", size: "M", price: 75000, stock: 220, images: [""] },
      { id: "pv7-6", sku: "KPP-RED-M", color: "Merah", size: "M", price: 75000, stock: 100, images: [""] },
    ],
  },
  {
    id: "p8",
    slug: "blender-portable-mini",
    name: "Blender Portable Mini USB",
    description: "Blender portable isi ulang via USB, kapasitas 400ml, pisau stainless steel, mudah dibawa ke mana saja.",
    categoryId: "c12",
    storeId: "s3",
    storeName: "Rumah Indah Shop",
    rating: 4.3,
    reviewCount: 2109,
    sold: 13500,
    images: ["", "", ""],
    tags: ["blender", "portable", "dapur"],
    variants: [
      { id: "pv8-1", sku: "BPM-PNK", color: "Pink", size: undefined, price: 149000, stock: 500, images: [""] },
      { id: "pv8-2", sku: "BPM-BLU", color: "Biru", size: undefined, price: 149000, stock: 450, images: [""] },
      { id: "pv8-3", sku: "BPM-GRN", color: "Hijau", size: undefined, price: 149000, stock: 300, images: [""] },
    ],
  },
];

export const shippingOptions: ShippingOption[] = [
  { id: "jne-reg", courier: "JNE", service: "REG", estimatedDays: "2-3 hari", price: 18000 },
  { id: "jne-yes", courier: "JNE", service: "YES (Same Day)", estimatedDays: "1 hari", price: 35000 },
  { id: "jnt-reg", courier: "J&T", service: "Regular", estimatedDays: "2-4 hari", price: 15000 },
  { id: "sicepat", courier: "SiCepat", service: "BEST", estimatedDays: "1-2 hari", price: 20000 },
  { id: "gosend", courier: "GoSend", service: "Same Day", estimatedDays: "Hari ini", price: 25000 },
];

export const mockAddresses: Address[] = [
  {
    id: "addr1",
    label: "Rumah",
    recipientName: "Budi Santoso",
    phone: "081234567890",
    street: "Jl. Sudirman No. 123, Kel. Karet Tengsin",
    city: "Jakarta Pusat",
    province: "DKI Jakarta",
    postalCode: "10220",
    isDefault: true,
  },
  {
    id: "addr2",
    label: "Kantor",
    recipientName: "Budi Santoso",
    phone: "081234567890",
    street: "Jl. Gatot Subroto Kav. 56",
    city: "Jakarta Selatan",
    province: "DKI Jakarta",
    postalCode: "12950",
    isDefault: false,
  },
];

export const mockOrders: Order[] = [
  {
    id: "ORD-2024-001",
    userId: "user1",
    items: [
      {
        productId: "p4",
        variantId: "pv4-1",
        productName: "Wireless Earbuds Pro ANC",
        variantLabel: "Hitam",
        price: 599000,
        quantity: 1,
        image: "",
        storeId: "s1",
        storeName: "TechStore Official",
      },
    ],
    address: mockAddresses[0],
    shippingMethod: "JNE REG",
    shippingCost: 18000,
    paymentMethod: "Transfer Bank BCA",
    subtotal: 599000,
    total: 617000,
    status: "delivered",
    createdAt: "2024-11-15T10:30:00Z",
  },
  {
    id: "ORD-2024-002",
    userId: "user1",
    items: [
      {
        productId: "p3",
        variantId: "pv3-2",
        productName: "Kemeja Casual Pria Premium",
        variantLabel: "Putih / M",
        price: 189000,
        quantity: 2,
        image: "",
        storeId: "s2",
        storeName: "Fashion Hub",
      },
    ],
    address: mockAddresses[0],
    shippingMethod: "J&T Regular",
    shippingCost: 15000,
    paymentMethod: "GoPay",
    subtotal: 378000,
    total: 393000,
    status: "shipped",
    createdAt: "2024-12-01T14:20:00Z",
  },
];

export const colorSwatches: Record<string, string> = colors;
